"""catalog — build an index of every spec with its status and score.

Phase 4 (Differentiate). Scans docs/specs and produces a single portfolio view
(docs/catalog.md) so a team can see, across all features, which specs are
complete, planned, reviewed, and how they score — the cross-cutting companion
to the per-feature `score` command.
"""

import sys
from pathlib import Path

from src.commands.score import compute_score


def run_catalog(target_dir_path: str | None) -> int:
    target_dir = Path(target_dir_path or ".").resolve()
    specs_dir = target_dir / "docs" / "specs"
    if not specs_dir.is_dir():
        print(f"Error: no specs directory found at '{specs_dir}'. Run `coding-spec init` first.", file=sys.stderr)
        return 1

    spec_files = sorted(specs_dir.glob("*.md"))
    catalog_file = target_dir / "docs" / "catalog.md"

    lines = [
        "# Spec Catalog",
        "",
        f"Index of {len(spec_files)} spec(s) under `docs/specs/`. Generated by `coding-spec catalog`.",
        "",
        "| Spec | Validated | Plan | Review | Coverage | Grade |",
        "|---|---|---|---|---|---|",
    ]

    graded = 0
    total_score = 0
    for spec_path in spec_files:
        card = compute_score(spec_path, target_dir)
        validated = "✅" if not card["errors"] else "❌"
        plan = "✅" if card["has_plan"] else "—"
        review = "✅" if card["has_review"] else "—"
        coverage = f"{card['criteria_covered']}/{card['criteria_total']}" if card["criteria_total"] else "—"
        lines.append(
            f"| `{card['slug']}` | {validated} | {plan} | {review} | {coverage} | **{card['grade']}** ({card['total']}) |"
        )
        graded += 1
        total_score += card["total"]

    if graded:
        avg = round(total_score / graded)
        lines += ["", f"**Portfolio average: {avg}/100 across {graded} spec(s).**"]
    else:
        lines += ["", "_No specs found. Run `coding-spec spec \"Your Feature\"` to add one._"]

    catalog_file.parent.mkdir(parents=True, exist_ok=True)
    catalog_file.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Wrote spec catalog ({graded} spec(s)) to: {catalog_file}")
    return 0
