"""ci — generate a CI workflow that runs `validate` as a required check.

Phase 3 (Automate). Writes a GitHub Actions workflow into the target repo so
that every push/PR gates its specs with `coding-spec validate --all` (and runs
the toolkit tests when present). This makes an incomplete spec block a merge
rather than relying on a reviewer to remember to run the check.
"""

import sys
from pathlib import Path

WORKFLOW = """\
# Generated by `coding-spec ci`. Runs the spec completeness gate on every push
# and pull request. Make this a required status check in branch protection to
# block merges when a spec is missing acceptance criteria or a test plan.
name: coding-spec

on:
  push:
    branches: [main]
  pull_request:

jobs:
  spec-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Validate all specs
        run: ./bin/coding-spec validate --all
      - name: Run toolkit tests
        run: |
          if [ -d tests ]; then python3 -m pytest tests/ -q; fi
"""


def run_ci(target_dir_path: str | None) -> int:
    target_dir = Path(target_dir_path or ".").resolve()
    workflow_file = target_dir / ".github" / "workflows" / "coding-spec.yml"

    if workflow_file.exists():
        print(f"Error: workflow already exists at '{workflow_file}'. Remove it first to regenerate.", file=sys.stderr)
        return 1

    workflow_file.parent.mkdir(parents=True, exist_ok=True)
    workflow_file.write_text(WORKFLOW, encoding="utf-8")
    print(f"Generated CI workflow at: {workflow_file}")
    print("  It runs `coding-spec validate --all` on push and pull_request.")
    print("  Mark the 'spec-gate' job as a required check in branch protection to enforce it.")
    return 0
